package fr.twentynine.keepon

import android.app.Application
import androidx.hilt.work.HiltWorkerFactory
import androidx.work.Configuration
import androidx.work.WorkManager
import coil3.ImageLoader
import coil3.PlatformContext
import coil3.SingletonImageLoader
import coil3.request.CachePolicy
import coil3.size.Precision
import dagger.hilt.android.EntryPointAccessors
import dagger.hilt.android.HiltAndroidApp
import fr.twentynine.keepon.domain.usecase.app.RunAppMigrationUseCase
import fr.twentynine.keepon.domain.gateway.WidgetUpdater
import fr.twentynine.keepon.ui.widget.component.clearWidgetTransitionCache
import fr.twentynine.keepon.core.coil.TimeoutIconDataFetcher
import fr.twentynine.keepon.core.coil.TimeoutIconDataKeyer
import fr.twentynine.keepon.di.entrypoint.StringResourceProviderEntryPoint
import fr.twentynine.keepon.core.worker.GuardianSystemScreenTimeoutWorkerScheduler
import fr.twentynine.keepon.core.worker.MonitorSystemScreenTimeoutWorkScheduler
import fr.twentynine.keepon.di.qualifier.ApplicationScope
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * The application entry point. Beyond Hilt setup it: schedules the screen-timeout monitor and
 * guardian workers and runs the one-time app migration on startup; provides the Coil [ImageLoader]
 * configured for the fully-generated timeout icons; provides the WorkManager configuration backed by
 * the Hilt worker factory; and releases the widget transition's bitmap holders on memory pressure.
 */
@HiltAndroidApp
class KeepOnApplication : Application(), SingletonImageLoader.Factory, Configuration.Provider {

    @Inject
    lateinit var hiltWorkerFactory: HiltWorkerFactory

    @Inject
    lateinit var runAppMigrationUseCase: RunAppMigrationUseCase

    @Inject
    lateinit var widgetUpdater: WidgetUpdater

    @Inject
    @ApplicationScope
    lateinit var applicationScope: CoroutineScope

    override fun onCreate() {
        super.onCreate()

        applicationScope.launch {
            val workManager = WorkManager.getInstance(this@KeepOnApplication.applicationContext)
            MonitorSystemScreenTimeoutWorkScheduler.scheduleWork(workManager)
            GuardianSystemScreenTimeoutWorkerScheduler.scheduleGuardianWork(workManager)

            runAppMigrationUseCase()
            widgetUpdater.requestUpdateWidgetPreview()
        }
    }

    override fun onTrimMemory(level: Int) {
        super.onTrimMemory(level)
        // Release the transition's out-of-Coil bitmap holders on any memory-pressure signal; they
        // rebuild lazily on the next draw (Coil trims its own cache via its ComponentCallbacks2).
        clearWidgetTransitionCache()
    }

    override fun newImageLoader(context: PlatformContext): ImageLoader {
        // The icons are fully generated by TimeoutIconDataFetcher (an ImageFetchResult),
        // so Coil's decode stage is bypassed: only the components and cache options below
        // are meaningful here. The string provider is resolved once for the fetcher factory.
        val stringResourceProvider = EntryPointAccessors.fromApplication(
            this.applicationContext,
            StringResourceProviderEntryPoint::class.java,
        ).stringResourceProvider()

        return ImageLoader.Builder(this.applicationContext)
            .components {
                add(TimeoutIconDataKeyer())
                add(TimeoutIconDataFetcher.Factory(stringResourceProvider))
            }
            .precision(Precision.INEXACT)
            .memoryCachePolicy(CachePolicy.ENABLED)
            .diskCachePolicy(CachePolicy.DISABLED)
            .build()
    }

    override val workManagerConfiguration: Configuration
        get() = Configuration.Builder()
            .setWorkerFactory(hiltWorkerFactory)
            .setWorkerCoroutineContext(Dispatchers.IO)
            .setDefaultProcessName(this.applicationInfo.processName)
            .build()
}
