package fr.twentynine.keepon

import android.app.Application
import androidx.hilt.work.HiltWorkerFactory
import androidx.work.Configuration
import androidx.work.WorkManager
import coil3.ImageLoader
import coil3.PlatformContext
import coil3.SingletonImageLoader
import coil3.request.CachePolicy
import coil3.size.Precision
import dagger.hilt.android.EntryPointAccessors
import dagger.hilt.android.HiltAndroidApp
import fr.twentynine.keepon.domain.usecase.app.RunAppMigrationUseCase
import fr.twentynine.keepon.domain.gateway.WidgetUpdater
import fr.twentynine.keepon.core.coil.TimeoutIconDataFetcher
import fr.twentynine.keepon.core.coil.TimeoutIconDataKeyer
import fr.twentynine.keepon.di.entrypoint.TimeoutIconDataFetcherEntryPoint
import fr.twentynine.keepon.core.worker.GuardianSystemScreenTimeoutWorkerScheduler
import fr.twentynine.keepon.core.worker.MonitorSystemScreenTimeoutWorkScheduler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import javax.inject.Inject
import kotlin.coroutines.CoroutineContext

@HiltAndroidApp
class KeepOnApplication : Application(), SingletonImageLoader.Factory, Configuration.Provider, CoroutineScope {

    @Inject
    lateinit var hiltWorkerFactory: HiltWorkerFactory

    @Inject
    lateinit var runAppMigrationUseCase: RunAppMigrationUseCase

    @Inject
    lateinit var widgetUpdater: WidgetUpdater

    val applicationScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    override val coroutineContext: CoroutineContext by lazy { applicationScope.coroutineContext }

    override fun onCreate() {
        super.onCreate()

        applicationScope.launch {
            val workManager = WorkManager.getInstance(this@KeepOnApplication.applicationContext)
            MonitorSystemScreenTimeoutWorkScheduler.scheduleWork(workManager)
            GuardianSystemScreenTimeoutWorkerScheduler.scheduleGuardianWork(workManager)

            runAppMigrationUseCase()
            widgetUpdater.requestUpdateWidgetPreview()
        }
    }

    override fun onTerminate() {
        super.onTerminate()

        applicationScope.cancel("Application is terminating")
    }

    override fun newImageLoader(context: PlatformContext): ImageLoader {
        // The icons are fully generated by TimeoutIconDataFetcher (an ImageFetchResult),
        // so Coil's decode stage is bypassed: only the components and cache options below
        // are meaningful here. The string provider is resolved once for the fetcher factory.
        val stringResourceProvider = EntryPointAccessors.fromApplication(
            this.applicationContext,
            TimeoutIconDataFetcherEntryPoint::class.java,
        ).stringResourceProvider()

        return ImageLoader.Builder(this.applicationContext)
            .components {
                add(TimeoutIconDataKeyer())
                add(TimeoutIconDataFetcher.Factory(stringResourceProvider))
            }
            .precision(Precision.INEXACT)
            .memoryCachePolicy(CachePolicy.ENABLED)
            .diskCachePolicy(CachePolicy.DISABLED)
            .build()
    }

    override val workManagerConfiguration: Configuration
        get() = Configuration.Builder()
            .setWorkerFactory(hiltWorkerFactory)
            .setWorkerCoroutineContext(Dispatchers.IO)
            .setDefaultProcessName(this.applicationInfo.processName)
            .build()
}
